### PR TITLE
commit update.sh

### PR DESCRIPTION
**Pull request by hwhitfield2**

### CODE REVIEW

**Comment by firealarmss** [comment]
Please add a comment recommending the use case of this script.

**Comment by hwhitfield2** [comment]
Updates config.example.yml with the current year, month, and date. `$(date +%Y-%m)` is stored as currentMonth, and `$(date +%d)` is stored as currentDate. That is updated in example.yml on new_logFiles. Kills the process and then relaunches it.

**Comment by firealarmss** [comment]
Please put that in the script as a comment

**Comment by hwhitfield2** [comment]
Line 2-5

> Please put that in the script as a comment

**Pull request merged**
